### ISSUE TITLE
death screen wont let you respawn

### ISSUE THREAD

**Issue by IAteMyShirt** [KubeloLive/Banov#3]
having an issue since i started to use your map on my server (great map). anytime me or the player on the server die theres no way to re-spawn they have to alt-f4 everytime>

heres my mod list

LaundryZ
DroneBatteryOverride
Drones
BuildingDoorKeys
WindstridesClothingPack
GCassettes
Radio
RTmerica
AICFireplaceIndoor
SurrenderInventory
Give&Take
DayZ-Dog
DayZ-Expansion-Chat
DayZ-Expansion-Groups
DayZ-Expansion-Book
DayZ-Expansion-BaseBuilding
DayZ-Expansion-Spawn-Selection
TDL Cars Pack
DayZ-Expansion-AI
RaG_BaseItems
DayZ-Expansion-Navigation
TakistanPlus
ZenSleep
CJ187-MoreItems
ArzzzWeapons
Furniture Kits [1.0]
Disable Zombie Climbing
GoreZ
Powerstrip
MagazineLoading
Ultimate MedicalStacking
DieselGear2.0
MoreBatteries
Dabs Framework
Big Grampa - Residential Aussie Houses
BuilderItems
BaseBuildingPlus
Search For Loot
DBN_BMW_X6M
DBN_MercedesG65_6x6 FREE
DBN_FordRaptor_Scorpio
MMG Retexture Pack Welliton
MMG Base Storage
Code Lock
ViewInventoryAnimation
ZenCauseOfDeath
VPPAdminTools
Zen's Firewood Piles
CannabisPlus
BulletStacksPlusPlus
BetterDrinks
ZenCatchRain
AdditionalMedicSupplies
SNAFU Weapons
MoreFood
OP_BaseItems
Mass'sManyItemOverhaul
Solar Panel Power System
MMG - Mightys Military Gear
BoomLay's Things
CF
BuildEverywhere
DayZ-Expansion-Market
DayZ-Expansion-Vehicles
DayZ-Expansion-Animations
DayZ-Expansion-Licensed
DayZ-Expansion
DayZ-Expansion-Core
Banov

**Comment by LincolnXue** [comment]
Try turning off the Expansion mod Bloody Hand.
