### ISSUE TITLE
The gas station on the map cannot be filled with empty tanks, and there is no prompt

### ISSUE THREAD

**Issue by xiaofengv233** [KubeloLive/Banov#6]
![ed8db1db2ce1fab139b00e1f59181241](https://github.com/KubeloLive/Banov/assets/24617660/e7ac49e8-425c-427d-9993-8e044d01e436)
The gas station on the map cannot be filled with empty tanks, and there is no prompt

**Comment by xiaofengv233** [comment]
All gas stations are the same

**Comment by philmriss78** [comment]
However, you can currently place those from Chernarus using the DayZ Editor

Land_FuelStation_Feed

others use the Discord. And we're living in an apocalypse, so raw materials can get tight at times

**Comment by xiaofengv233** [comment]
> However, you can currently place those from Chernarus using the DayZ Editor
> 
> Land_FuelStation_Feed
> 
> others use the Discord. And we're living in an apocalypse, so raw materials can get tight at times

Thanks

**Comment by xiaofengv233** [comment]
> However, you can currently place those from Chernarus using the DayZ Editor
> 
> Land_FuelStation_Feed
> 
> others use the Discord. And we're living in an apocalypse, so raw materials can get tight at times

Hello, how can I adjust the refresh time of the fortress. Now I need to restart the server to refresh.

**Comment by KubeloLive** [comment]
fixed
